version: '3'
services:
    mongo:
        image: mongo:5.0
        restart: always
        ports:
            - 27017:27017
        volumes:
            - $PWD/db:/data/db 
    server: 
        depends_on: 
            - mongo
        build: .
        restart: always
        container_name: nodejs_jwt_app
        environment: 
            PORT: 8017
            DB_URI: "mongodb://mongo:27017/todo"
        ports:
            - 8017:8017